/* 
 * decksite API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using PennyDreadfulMagic.Decksite.Client;
using PennyDreadfulMagic.Decksite.Model;

namespace PennyDreadfulMagic.Decksite.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Competition</returns>
        Competition GetLeague (string xFields = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>ApiResponse of Competition</returns>
        ApiResponse<Competition> GetLeagueWithHttpInfo (string xFields = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deckId"></param>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Deck</returns>
        Deck GetLoadDeck (int? deckId, string xFields = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deckId"></param>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>ApiResponse of Deck</returns>
        ApiResponse<Deck> GetLoadDeckWithHttpInfo (int? deckId, string xFields = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Task of Competition</returns>
        System.Threading.Tasks.Task<Competition> GetLeagueAsync (string xFields = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Task of ApiResponse (Competition)</returns>
        System.Threading.Tasks.Task<ApiResponse<Competition>> GetLeagueAsyncWithHttpInfo (string xFields = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deckId"></param>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Task of Deck</returns>
        System.Threading.Tasks.Task<Deck> GetLoadDeckAsync (int? deckId, string xFields = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deckId"></param>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Task of ApiResponse (Deck)</returns>
        System.Threading.Tasks.Task<ApiResponse<Deck>> GetLoadDeckAsyncWithHttpInfo (int? deckId, string xFields = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDefaultApi
    {
        private PennyDreadfulMagic.Decksite.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(String basePath)
        {
            this.Configuration = new PennyDreadfulMagic.Decksite.Client.Configuration { BasePath = basePath };

            ExceptionFactory = PennyDreadfulMagic.Decksite.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(PennyDreadfulMagic.Decksite.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = PennyDreadfulMagic.Decksite.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = PennyDreadfulMagic.Decksite.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public PennyDreadfulMagic.Decksite.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public PennyDreadfulMagic.Decksite.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Competition</returns>
        public Competition GetLeague (string xFields = null)
        {
             ApiResponse<Competition> localVarResponse = GetLeagueWithHttpInfo(xFields);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>ApiResponse of Competition</returns>
        public ApiResponse< Competition > GetLeagueWithHttpInfo (string xFields = null)
        {

            var localVarPath = "./league";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xFields != null) localVarHeaderParams.Add("X-Fields", this.Configuration.ApiClient.ParameterToString(xFields)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLeague", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Competition>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (Competition) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Competition)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Task of Competition</returns>
        public async System.Threading.Tasks.Task<Competition> GetLeagueAsync (string xFields = null)
        {
             ApiResponse<Competition> localVarResponse = await GetLeagueAsyncWithHttpInfo(xFields);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Task of ApiResponse (Competition)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Competition>> GetLeagueAsyncWithHttpInfo (string xFields = null)
        {

            var localVarPath = "./league";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xFields != null) localVarHeaderParams.Add("X-Fields", this.Configuration.ApiClient.ParameterToString(xFields)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLeague", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Competition>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (Competition) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Competition)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deckId"></param>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Deck</returns>
        public Deck GetLoadDeck (int? deckId, string xFields = null)
        {
             ApiResponse<Deck> localVarResponse = GetLoadDeckWithHttpInfo(deckId, xFields);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deckId"></param>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>ApiResponse of Deck</returns>
        public ApiResponse< Deck > GetLoadDeckWithHttpInfo (int? deckId, string xFields = null)
        {
            // verify the required parameter 'deckId' is set
            if (deckId == null)
                throw new ApiException(400, "Missing required parameter 'deckId' when calling DefaultApi->GetLoadDeck");

            var localVarPath = "./decks/{deck_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (deckId != null) localVarPathParams.Add("deck_id", this.Configuration.ApiClient.ParameterToString(deckId)); // path parameter
            if (xFields != null) localVarHeaderParams.Add("X-Fields", this.Configuration.ApiClient.ParameterToString(xFields)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLoadDeck", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Deck>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (Deck) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Deck)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deckId"></param>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Task of Deck</returns>
        public async System.Threading.Tasks.Task<Deck> GetLoadDeckAsync (int? deckId, string xFields = null)
        {
             ApiResponse<Deck> localVarResponse = await GetLoadDeckAsyncWithHttpInfo(deckId, xFields);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="PennyDreadfulMagic.Decksite.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deckId"></param>
        /// <param name="xFields">An optional fields mask (optional)</param>
        /// <returns>Task of ApiResponse (Deck)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Deck>> GetLoadDeckAsyncWithHttpInfo (int? deckId, string xFields = null)
        {
            // verify the required parameter 'deckId' is set
            if (deckId == null)
                throw new ApiException(400, "Missing required parameter 'deckId' when calling DefaultApi->GetLoadDeck");

            var localVarPath = "./decks/{deck_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (deckId != null) localVarPathParams.Add("deck_id", this.Configuration.ApiClient.ParameterToString(deckId)); // path parameter
            if (xFields != null) localVarHeaderParams.Add("X-Fields", this.Configuration.ApiClient.ParameterToString(xFields)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLoadDeck", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Deck>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (Deck) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Deck)));
        }

    }
}
