// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PennyDreadfulMagic.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DecklistEntry
    {
        /// <summary>
        /// Initializes a new instance of the DecklistEntry class.
        /// </summary>
        public DecklistEntry()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DecklistEntry class.
        /// </summary>
        public DecklistEntry(int? n = default(int?), string name = default(string))
        {
            N = n;
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "n")]
        public int? N { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
